config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    devise_for :admins, controllers: {
    sessions: 'admin/admins/sessions',
    registrations: 'admin/admins/registrations',
    passwords: 'admin/admins/passwords'
  }
end
  
  
  namespace :admin do
    resources :calories
    resources :users, only: [:index, :show, :edit, :update]
    root to: 'home#top'
  end
  
  
  devise_for :users
  resources :users
  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resource :comments,only: [:create, :destroy]
  end
  
  get 'user/calories' => 'calories#index', as: 'calories'
  get 'search' => 'search#search'
  
  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す

  get 'users/:id/follow' =>'users#follow', as: 'follows'

  get 'users/:id/followed'=>'users#followed', as: 'followed'

  get 'user/withdraw' => 'users#withdraw', as: 'withdraw_user'

  patch 'user/change' => 'users#change', as: 'users_change'

  root to: "home#top"
  get 'home/about' => 'home#about', as: 'about'

  get 'userpass/reset' => 'reset#send', as: 'reset_userpass'

  put 'userpass/reset' => 'reset#send', as: 'user_reset_userpass'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calorie.rb
class Calorie < ApplicationRecord

    validates :name, presence: true
    validates :calorie, numericality: {only_integer: true}
    validates :weight, numericality: {only_integer: true}
    validates :is_active, inclusion: {in: [true, false]}
    validates :yomi, presence: true

    def self.search(search)
      if search
        Calorie.where(['name LIKE ?', "%#{search}%"])
      else
        Calorie.all
      end
    end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :comments,dependent: :destroy
  attachment :image

  with_options presence: true do
    validates :title
    validates :body
    validates :procedure
    validates :material
    validates :image
  end
  validates :calorie, numericality: {only_integer: true}
  validates :is_light, inclusion: {in: [true, false]}
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments,dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  validates :username, presence: true
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人
  
  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

# ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

# フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end

  def already_favorited?(post)
    self.favorites.exists?(post_id: post.id)
  end

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

  def unsubscribe!
    
    ActiveRecord::Base.transaction do
      update!(is_deleted:true)
      comments.each do |comment| 
      comment.destroy! 
      end

      followed.each do |follow| 
        follow.destroy! 
      end

      follower.each do |follow| 
        follow.destroy! 
      end

      favorites.each do |favorite| 
        favorite.destroy! 
      end
        
      posts.each do |post| 
        post.destroy! 
      end

      
    end
    begin
      # 成功時
    rescue => e
      Rails.logger.info "Rendering 500 with Exception: #{e}"
    end
  end
end

app/controllers/admin/calories_controller.rb
class Admin::CaloriesController < ApplicationController
  before_action :authenticate_admin_admin!
  
  def index
    @calories = Calorie.order("yomi")

  end
  
  def new
    @calorie = Calorie.new
  end

  def create
    @calorie = Calorie.new(calorie_params)
    if @calorie.save
      redirect_to admin_calories_path
    else
    render :new
    end
  end

  def edit
    @calorie =Calorie.find(params[:id])
  end

  def update
    @calorie = Calorie.find(params[:id])
    if @calorie.update(calorie_params)
      redirect_to admin_calories_path
    else
      render :edit
    end
  end

  def destroy
    calorie = Calorie.find(params[:id])
    calorie.destroy
    redirect_to admin_calories_path
  end



private
  def calorie_params
    params.require(:calorie).permit(:name, :weight, :calorie,:yomi, :is_active)
  end
end

app/controllers/calories_controller.rb
class CaloriesController < ApplicationController

  def index
    @calories = Calorie.page(params[:page]).per(10).where(is_active: true).order(:yomi)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @all_ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(4).pluck(:post_id))
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @posts = Post.page(params[:page]).per(4)
    if params[:is_light].present?
      @posts = Post.where(is_light: params[:is_light]).page(params[:page]).per(4)
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @user = @post.user
    
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
    redirect_to post_path(@post), notice: "投稿しました"
    else
    render :new
    end
  end
  
  def edit
    @post = Post.find(params[:id])
    if @post.user != current_user
      redirect_to posts_path,alert: '不正なアクセスです'
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
    redirect_to post_path(@post), notice: "更新しました"
    else
    render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :calorie, :body, :image, :material, :procedure, :is_light)
  end

end

app/controllers/reset_controller.rb
class ResetController < ApplicationController

def send

end





end

app/helpers/admin/calories_helper.rb
module Admin::CaloriesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calories_helper.rb
module CaloriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_alert(key)
    case key
    when "alert"
      "warning"
    when "notice"
      "success"
    when "error"
      "danger"
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reset_helper.rb
module ResetHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/calories/edit.html.erb
<div class="container">
<h2>カロリー編集</h2>
  <div class="row mt-5">
      <% if @calorie.errors.any? %>
        <%= pluralize(@calorie.errors.count, "error") %> prohibited this object from being saved: not successfully

        <% @calorie.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      <% end %>

      <%= form_for @calorie, url:admin_calory_path, method: :patch do |f|%>
        <table>
          <tr class="tr-size col mt-3">
            <td width="70"><%=f.label :name, "材料名" %><td>
            <td><%=f.text_field :name %></td>
          </tr>
          <tr class="tr-size col mt-3">
            <td width="70"><%=f.label :yomi, "ふりがな" %><td>
            <td><%=f.text_field :yomi %></td>
          </tr>
          <tr class="tr-size col mt-3">
            <td width="70"><%=f.label :weight, "重量" %></td>
            <td><%=f.text_field :weight %>g</td>
          </tr>
          <tr class="tr-size col mt-3">
              <td width="70">カロリー</td>
            <td><%=f.text_field :calorie %>Kcal</td>
          </tr>
          <tr class="tr-size col mt-3">  
            <td><%=f.label :"カテゴリー" %>
              <%=f.radio_button :is_active, :true %>
                <%=f.label:有効,class: "is_active_label" %>
              <%=f.radio_button :is_active, :false %>
                <%=f.label:無効,class: "is_active_label" %>
            </td>
          </tr>
          <tr>
            <td>
              <%=f.submit %>
            </td>
          </tr>
        </table>
      <% end %>


  </div>
</div>

app/views/admin/calories/index.html.erb
<div class="container">
  <div class="row">
  <div class="col-lg-4">
    <h2 class="mb-5">カロリー一覧</h2>
  </div>
    
        <table class="table table-hover">
          <tr>
            <th>食材</th>
            <th>重量（g）</th>
            <th>Kcal</th>  
            <th>ステータス</th>
          </tr> 
          <% @calories.each do |calorie| %>
            <tr>
              <td><%=calorie.name%></td>      
              <td><%=calorie.weight%>g</td>
              <td><%=calorie.calorie%>Kcal</td>
              <td>
                <% if calorie.is_active ==true %>
                  有効
                <% else %>
                  無効
                <% end %>
              </td>
              <td>
                <%=link_to"編集",edit_admin_calory_path(calorie)%>
                  <%=link_to "削除",admin_calory_path(calorie), method: :delete, data: {confirm: "削除しますか？"} %>
              </td>
            </tr>
          <% end %>                   
        </table> 
    
  </div>
</div>

app/views/admin/calories/new.html.erb
<div class="container">
<h2>カロリー登録</h2>
  <div class="row mt-5">
      <% if @calorie.errors.any? %>
        <%= pluralize(@calorie.errors.count, "error") %> prohibited this object from being saved: not successfully

        <% @calorie.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      <% end %>

      <%=form_for @calorie, url:admin_calories_path, method: :post do |f| %>
        <table>
          <tr class="tr-size col mt-3">
            <td width="70"><%=f.label :name, "材料名" %><td>
            <td><%=f.text_field :name %></td>
          </tr>
          <tr class="tr-size col mt-3">
            <td width="70"><%=f.label :yomi, "ふりがな" %><td>
            <td><%=f.text_field :yomi %></td>
          </tr>
          <tr class="tr-size col mt-3">
            <td width="70"><%=f.label :weight, "重量" %></td>
            <td><%=f.text_field :weight %>g</td>
          </tr>
          <tr class="tr-size col mt-3">
            <td width="70">カロリー</td>
            <td><%=f.text_field :calorie %>Kcal</td>
          </tr>
          <tr class="tr-size col mt-3">
            <td><%=f.label :"カテゴリー" %>
              <%=f.radio_button :is_active, :true %>
                <%=f.label:有効,class: "is_active_label" %>
              <%=f.radio_button :is_active, :false %>
                <%=f.label:無効,class: "is_active_label" %>
            </td>
          </tr>
          <tr>
            <td>
              <%=f.submit %>
            </td>
          </tr>
        </table>
        <% end %>
  </div>
</div>

app/views/calories/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-4">
      <h2 class>カロリー一覧</h2>
      <p class="mb-5">(五十音順並び）</p>
      </div>
  </div>

<div class="row mb-3 offset-3">
  <p>検索</p>
  <%= form_tag(search_path, method: :get) do %>
    <%= text_field_tag :search, '',:size=>"30x5",placeholder: 'Search'%>
  <% end %>
</div>

  <div class="row">
    <div class="col-8 offset-2">      
        <table class="table table-hover">
          <tr>
            <th>食材</th>
            <th>重量（g）</th>
            <th>Kcal</th>  
          </tr> 
          <tr>
            <% @calories.each do |calorie| %>
              <td>
                <%=calorie.name%>
              </td>
              <td>
                <%=calorie.weight%>g
              </td>
              <td>
                <%=calorie.calorie%>Kcal
              </td>
            </tr>
            <% end %>
        </table>
        <%= paginate @calories %>
    </div>    
  </div>