config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    devise_for :admins, controllers: {
    sessions: 'admin/admins/sessions',
    registrations: 'admin/admins/registrations',
    passwords: 'admin/admins/passwords'
  }
end
  
  
  namespace :admin do
    resources :calories
    resources :users, only: [:index, :show, :edit, :update]
    root to: 'home#top'
  end
  
  
  devise_for :users
  resources :users
  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resource :comments,only: [:create, :destroy]
  end
  
  get 'user/calories' => 'calories#index', as: 'calories'
  get 'search' => 'search#search'
  
  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す

  get 'users/:id/follow' =>'users#follow', as: 'follows'

  get 'users/:id/followed'=>'users#followed', as: 'followed'

  get 'user/withdraw' => 'users#withdraw', as: 'withdraw_user'

  patch 'user/change' => 'users#change', as: 'users_change'

  root to: "home#top"
  get 'home/about' => 'home#about', as: 'about'

  get 'userpass/reset' => 'reset#send', as: 'reset_userpass'

  put 'userpass/reset' => 'reset#send', as: 'user_reset_userpass'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calorie.rb
class Calorie < ApplicationRecord

    validates :name, presence: true
    validates :calorie, numericality: {only_integer: true}
    validates :weight, numericality: {only_integer: true}
    validates :is_active, inclusion: {in: [true, false]}
    validates :yomi, presence: true

    def self.search(search)
      if search
        Calorie.where(['name LIKE ?', "%#{search}%"])
      else
        Calorie.all
      end
    end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :comments,dependent: :destroy
  attachment :image

  with_options presence: true do
    validates :title
    validates :body
    validates :procedure
    validates :material
    validates :image
  end
  validates :calorie, numericality: {only_integer: true}
  validates :is_light, inclusion: {in: [true, false]}
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments,dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  validates :username, presence: true
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人
  
  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

# ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

# フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end

  def already_favorited?(post)
    self.favorites.exists?(post_id: post.id)
  end

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

  def unsubscribe!
    
    ActiveRecord::Base.transaction do
      update!(is_deleted:true)
      comments.each do |comment| 
      comment.destroy! 
      end

      followed.each do |follow| 
        follow.destroy! 
      end

      follower.each do |follow| 
        follow.destroy! 
      end

      favorites.each do |favorite| 
        favorite.destroy! 
      end
        
      posts.each do |post| 
        post.destroy! 
      end

      
    end
    begin
      # 成功時
    rescue => e
      Rails.logger.info "Rendering 500 with Exception: #{e}"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @all_ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(4).pluck(:post_id))
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @posts = Post.page(params[:page]).per(4)
    if params[:is_light].present?
      @posts = Post.where(is_light: params[:is_light]).page(params[:page]).per(4)
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @user = @post.user
    
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
    redirect_to post_path(@post), notice: "投稿しました"
    else
    render :new
    end
  end
  
  def edit
    @post = Post.find(params[:id])
    if @post.user != current_user
      redirect_to posts_path,alert: '不正なアクセスです'
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
    redirect_to post_path(@post), notice: "更新しました"
    else
    render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :calorie, :body, :image, :material, :procedure, :is_light)
  end

end

app/controllers/reset_controller.rb
class ResetController < ApplicationController

def send

end





end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  
  def follow
    @user = User.find(params[:id])
  end

  def followed
    @user = User.find(params[:id])
  end
  
  def index
    @users = User.page(params[:page]).per(4).where(is_deleted: false)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to users_path, alert: '不正なアクセスです'
    end
  end

  def update
    @user = User.find(params[:id])
    if@user.update(user_params)
    redirect_to user_path(@user)
    else
    render :edit
    end
  end 

  def withdraw
  end
  
  def change
    current_user.unsubscribe!
      sign_out current_user
    redirect_to root_path
    
  end

private 
  def user_params
    params.require(:user).permit(:username,:email,:profile,:profile_image,:is_deleted)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calories_helper.rb
module CaloriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_alert(key)
    case key
    when "alert"
      "warning"
    when "notice"
      "success"
    when "error"
      "danger"
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/reset_helper.rb
module ResetHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/edit.html.erb
<div class="container">
  <h1>Recipe 編集</h1>
    <%=link_to "Back",post_path(@post)%>
    <div class="row mt-5">
      <div class="col-lg-12 offset-2">
        
        <% if @post.errors.any? %>
          <%= pluralize(@post.errors.count, "error") %> prohibited this object from being saved: not successfully

          <% @post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        <% end %>

          <%= form_for @post do |f|%>
            <table> 
              <tr class="tr-size">
                <td width="90"><%=f.label :レシピ名 %></td>
                <td width="200"><%=f.text_field :title %></td>
                <td width="90"><%=f.label :"カテゴリー" %></td>
                <td>
                  <%=f.radio_button :is_light, :false %>
                  <%=f.label:増量,class: "is_light_label" %>
                  <%=f.radio_button :is_light, :true %>
                  <%=f.label:減量,class: "is_light_label" %>
                </td>
              </tr>
              
              <tr class="tr-size">
                <td width="90"><%=f.label :カロリー %></td>
                <td><%=f.text_field :calorie %>kcal</td>
              </tr>
    
              <tr class="tr-size">
                <td width="90"><%=f.label :写真 %></td>           
                  <td>
                    <%= attachment_image_tag @post, :image, :fill, 250,200, format: "jpeg", fallback: 'no-image.png', onClick: "$('.img_field').click()", class: "center-block img-thumbnail img-responsive img_prev pull-left profile-img", fallback: "no_image.jpg", :width => "250", :height => "200" %> 
                  <%=f.attachment_field :image, class: 'img_field' %>
                </td>
              </tr>

              <tr class="tr-size">
                <td width="90"><%=f.label :説明 %></td>
                <td><%=f.text_area :body,:size=>"50x10" %></td>
              </tr>

              <tr class="tr-size">
                <td  width="90"><%=f.label :材料 %></td>               
                <td><%=f.text_area :material,:size=>"50x10" %></td>
              </tr>

              <tr class="tr-size">
                <td width="90"><%=f.label :作り方 %></td>
                <td><%=f.text_area :procedure,:size=>"50x10" %></td>
              </tr>           
            </table>
              <div class="col offset-5">
                <%=f.submit "更新", class: "btn btn-primary"%>
              </div>
          <% end %>
      </div>
    </div>
</div>

app/views/posts/index.html.erb
<div class="container">
    <h1>レシピ一覧</h1>
  <div class="row mt-5">
    
    <h4 class="col-lg-2">
      <%if params[:is_light] == "false" %>
       増量メニュー<br><%=link_to"一覧へ戻る",posts_path %>
      <%elsif params[:is_light] == "true" %>
        減量メニュー<br><%=link_to"一覧へ戻る",posts_path %>
      <%end %>
        <div>
          <%= link_to '減量', posts_path(is_light: true),class: "btn btn-primary btn-lg" %>
        </div><br>
        <div>
          <%= link_to '増量', posts_path(is_light: false),class: "btn btn-danger btn-lg" %>
        </div>     
    </h4>  
    <div class="col-lg-10 offset-lg-4">
      <table>
        <% @posts.each do |post| %>
          <tr>
            <td>             
              <%=attachment_image_tag post, :image, size: "350x350" %>
            </td>
            <td>
              <%=link_to user_path(post.user.id) do %>
                <%=attachment_image_tag post.user, :profile_image,size: "80x80", format: 'jpeg', class: "rounded-circle pull-left profile-img", fallback: "no_image.jpg",size: "100x100" %>
              <% end %>
            </td>
            <td>
              <%=link_to user_path(post.user.id) do %>
                <%=post.user.username %>
              <% end %>
            </td>
          </tr>
          <tr>
            <td>
              <%=link_to post_path(post) do %>
                <%=post.title%>
              <% end %>
            <td>
          <tr>

          <tr>
            <td>
              <% if post.is_light==false %>
                （増量レシピ）
              <% else %>
                （減量レシピ）
              <% end %>

              <% if current_user.already_favorited?(post) %>
                <%= link_to post_favorites_path(post), method: :delete do %>
                  <i class="fas fa-heart"></i>
                <% end %>
              <% else %>
                <%= link_to post_favorites_path(post), method: :post do %>
                  <i class="far fa-heart"></i>
                <% end %>
              <% end %>
              <%=post.favorites.count%>
            </td>
          </tr>
          <tr>
            <td>
              <%=post.comments.count%>コメント 
            </td>
          </tr>
          <tr>
            <td>
              <%=post.updated_at.strftime("%Y-%m-%d %H:%M") %>更新
            </td>
          </tr>                
        <% end %>
      </table>
      <%= paginate @posts %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <h1>New Recipe</h1>
    <div class="row mt-5">
      <div class="col-lg-12 offset-3">
            <% if @post.errors.any? %>
              <%= pluralize(@post.errors.count, "error") %> prohibited this object from being saved: not successfully

              <% @post.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            <% end %>

            <%=form_for @post do |f| %>
            <table>
              
              <tr>
                <td><%=f.label :title, "レシピ名" %></td>
                <td><%=f.text_field :title %>
                <%=f.label :"カテゴリー" %>
                <%=f.radio_button :is_light, :false %>
                <%=f.label:増量,class: "is_light_label" %>
                  <%=f.radio_button :is_light, :true %>
                  <%=f.label:減量,class: "is_light_label" %>
                </td>
              </tr>

              <tr>
                <td><%=f.label :calorie, "カロリー" %></td>
                <td><%=f.text_field :calorie %>kcal</td>
              </tr> 
              <tr>
                <td><%=f.label :body, "説明" %></td>
                <td><%=f.text_area :body, :size=>"50x10"%></td>
              </tr>
      </div>
    </div>    

              <tr>
                <td><%=f.label :image, "写真" %></td>
                <td>
                  <%= attachment_image_tag @post, :image, :fill, 200,200, format: "jpeg", fallback: 'no-image.png', onClick: "$('.img_field').click()", class: "center-block img-thumbnail img-responsive img_prev pull-left profile-img", fallback: "no_image.jpg", :width => "200", :height => "200" %>
                  <%=f.attachment_field :image, class: 'img_field' %>
                </td>
              </tr>

              <tr>
                <td><%=f.label :material, "材料" %></td>
                <td><%=f.text_area :material,:size=>"50x10" %></td>
              </tr>

              <tr>
                <td><%=f.label :procedure, "作り方" %></td>
                <td><%=f.text_area :procedure,:size=>"50x10" %></td>
              <tr>
            </table>
              <div class="row offset-5">
                <%=f.submit "投稿", class: "btn btn-primary" %>
              </div>
            <% end %>
</div>

app/views/posts/show.html.erb
<div class="container">
  <h1>Recipe detail</h1>
    <%=link_to user_path(@post.user) do %>
      <%=@post.user.username%>さんのページへ
    <% end %>
    <div class="row mt-3 offset-2">    
      <div class="col-lg-10">
        <table>
          <tr class="tr-size">
            <th width="90">レシピ名</th>
            <td width="220"><%=@post.title %> 
              <% if @post.is_light==false %>
                （増量レシピ）
              <% else %>
                （減量レシピ）
              <% end %></td>
            <th width="70">材料</th>
            <td width="180"><%=simple_format @post.material %></td>
          </tr>
          <tr class="tr-size" >
            <th width="90">カロリー</th>
            <td width="260"><%=@post.calorie %>kcal</td>           
          </tr>
      </div>
    </div>
        
          <tr class="tr-size" >
            <td><%=attachment_image_tag @post, :image, size: "300x300" %></td>
            <th width="70">説明</th>
            <td width="250"><%=simple_format @post.body %></td>
          </tr>

          <tr class="tr-size">
            <th width="90">作り方</th>
            <td><%=simple_format @post.procedure %></td>
          </tr>

          <tr class="tr-size">
            <th>いいね</th>
            <td>
              <% if current_user.already_favorited?(@post) %>
                <%= link_to post_favorites_path(@post),method: :delete do %>
                  <i class="fas fa-heart"></i>
                <% end %>
              <% else %>
                <%= link_to post_favorites_path(@post),method: :post do %>
                <i class="far fa-heart"></i>
                <% end %>
              <% end %>
              <%= @post.favorites.count%>
            </td>
          </tr>
          <tr>
            <th>更新日</th>
          </tr>
          <tr class= "row mb-5 ">
            <td ><%=@post.updated_at.strftime("%Y-%m-%d %H:%M") %></td>
          </tr>

          
          <% @post.comments.each do |comment| %>
            <tr>
              <th>コメント<th>
            </tr>
            <tr class="tr-size">
              <td width="270" ><%= comment.comment %></td>
              <td><% if comment.user == current_user %>
                <%= link_to"消去",post_comments_path(comment), method: :delete,class: "btn btn-danger" %>
                <% end %>
              </td>
              <td>ユーザー：
                <%= link_to user_path(@user) do %>
                  <%=comment.user.username%>
                <% end %>
              </td>
            </tr> 
          <% end %>
        </table>

        <%= form_for [@post, @comment] do |f| %>
              <%= f.text_area :comment, :size=>"30x5",placeholder: "コメントを入力してください" %>
            <%= f.submit "送信" %>
            <% end %>


        <% if @post.user.id == current_user.id%>
          <%=link_to"編集",edit_post_path(@post), class: "btn btn-success" %>
        <% end %>




</div>