config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    devise_for :admins, controllers: {
    sessions: 'admin/admins/sessions',
    registrations: 'admin/admins/registrations',
    passwords: 'admin/admins/passwords'
  }
end
  
  
  namespace :admin do
    resources :calories
    resources :users, only: [:index, :show, :edit, :update]
    root to: 'home#top'
  end
  
  
  devise_for :users
  resources :users
  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resource :comments,only: [:create, :destroy]
  end
  
  get 'user/calories' => 'calories#index', as: 'calories'
  get 'search' => 'search#search'
  
  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す

  get 'users/:id/follow' =>'users#follow', as: 'follows'

  get 'users/:id/followed'=>'users#followed', as: 'followed'

  get 'user/withdraw' => 'users#withdraw', as: 'withdraw_user'

  patch 'user/change' => 'users#change', as: 'users_change'

  root to: "home#top"
  get 'home/about' => 'home#about', as: 'about'

  get 'userpass/reset' => 'reset#send', as: 'reset_userpass'

  put 'userpass/reset' => 'reset#send', as: 'user_reset_userpass'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calorie.rb
class Calorie < ApplicationRecord

    validates :name, presence: true
    validates :calorie, numericality: {only_integer: true}
    validates :weight, numericality: {only_integer: true}
    validates :is_active, inclusion: {in: [true, false]}
    validates :yomi, presence: true

    def self.search(search)
      if search
        Calorie.where(['name LIKE ?', "%#{search}%"])
      else
        Calorie.all
      end
    end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :comments,dependent: :destroy
  attachment :image

  with_options presence: true do
    validates :title
    validates :body
    validates :procedure
    validates :material
    validates :image
  end
  validates :calorie, numericality: {only_integer: true}
  validates :is_light, inclusion: {in: [true, false]}
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments,dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  validates :username, presence: true
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人
  
  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

# ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

# フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end

  def already_favorited?(post)
    self.favorites.exists?(post_id: post.id)
  end

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

  def unsubscribe!
    
    ActiveRecord::Base.transaction do
      update!(is_deleted:true)
      comments.each do |comment| 
      comment.destroy! 
      end

      followed.each do |follow| 
        follow.destroy! 
      end

      follower.each do |follow| 
        follow.destroy! 
      end

      favorites.each do |favorite| 
        favorite.destroy! 
      end
        
      posts.each do |post| 
        post.destroy! 
      end

      
    end
    begin
      # 成功時
    rescue => e
      Rails.logger.info "Rendering 500 with Exception: #{e}"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @all_ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(4).pluck(:post_id))
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @posts = Post.page(params[:page]).per(4)
    if params[:is_light].present?
      @posts = Post.where(is_light: params[:is_light]).page(params[:page]).per(4)
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @user = @post.user
    
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
    redirect_to post_path(@post), notice: "投稿しました"
    else
    render :new
    end
  end
  
  def edit
    @post = Post.find(params[:id])
    if @post.user != current_user
      redirect_to posts_path,alert: '不正なアクセスです'
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
    redirect_to post_path(@post), notice: "更新しました"
    else
    render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :calorie, :body, :image, :material, :procedure, :is_light)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calories_helper.rb
module CaloriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_alert(key)
    case key
    when "alert"
      "warning"
    when "notice"
      "success"
    when "error"
      "danger"
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reset_helper.rb
module ResetHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
<div class="alert alert-<%= bootstrap_alert(key) %>">
  <%= value %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BodyRecipe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
  </head>

  <body>
    <header class= "sticky-top">
      <nav class="nav navbar-nav navbar-left" style="background-color: #FFCC66;">
        <h2 class="title is-4" style="font-family: fantasy;">BodyRecipe</h2>

      <ul class="navbar-expand-lg">
      
      <% if user_signed_in? %>

        <li>
          <%=link_to root_path do %>
            <i class="fas fa-home"></i>Home
          <% end %>
        </li>
        
        <li><%=link_to posts_path do%>
            <i class="far fa-newspaper"></i>投稿一覧
            <%end%>
        </li>
        <li><%=link_to new_post_path do%>
              <i class="fas fa-edit"></i>投稿する
            <% end %>
        </li>      
        <li><%=link_to users_path do %>
              <i class="fas fa-users"></i>シェフ
            <% end %>
        </li>      
        <li><%=link_to user_path(current_user) do %>
              <i class="fas fa-user"></i>マイページ
            <% end %>
        </li>
        <li><%=link_to calories_path do %>
              <i class="fas fa-utensils"></i>カロリー
            <% end %>
        </li>
        <li><%= link_to destroy_user_session_path,method: :delete do %>
              <i class="fas fa-sign-out-alt"></i>ログアウト
            <% end %>
        </li>
      <% elsif admin_admin_signed_in? %>
        <li><%= link_to "食材一覧",admin_calories_path %></li>
        <li><%= link_to "食材登録",new_admin_calory_path %></li>
        <li><%= link_to "会員一覧",admin_users_path %></li>
        <li><%= link_to "ログアウト", destroy_admin_admin_session_path, method: :delete %></li>
      
      <%else%>

      <li>
          <%=link_to root_path do %>
            <i class="fas fa-home"></i>Home
          <% end %>
        </li>

        <li>
          <%=link_to about_path do %>
            <i class="fas fa-link"></i>サイトについて
          <% end %>
        </li>
        <li>
          <%=link_to new_user_session_path  do%>
            <i class="fas fa-sign-in-alt"></i>ログイン
          <% end %>
        </li>
        <li><%=link_to new_user_registration_path do%>
              <i class="fas fa-user-edit"></i>新規登録
            <% end %>
        </li>
      <% end %>
    </ul>
    </nav>
  </header>
  <%= render 'layouts/flashes' %>
  
    <%= yield %>
  
  </body>
</html>