config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    devise_for :admins, controllers: {
    sessions: 'admin/admins/sessions',
    registrations: 'admin/admins/registrations',
    passwords: 'admin/admins/passwords'
  }
end
  
  
  namespace :admin do
    resources :calories
    resources :users, only: [:index, :show, :edit, :update]
    root to: 'home#top'
  end
  
  
  devise_for :users
  resources :users
  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resource :comments,only: [:create, :destroy]
  end
  
  get 'user/calories' => 'calories#index', as: 'calories'
  get 'search' => 'search#search'
  
  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す

  get 'users/:id/follow' =>'users#follow', as: 'follows'

  get 'users/:id/followed'=>'users#followed', as: 'followed'

  get 'user/withdraw' => 'users#withdraw', as: 'withdraw_user'

  patch 'user/change' => 'users#change', as: 'users_change'

  root to: "home#top"
  get 'home/about' => 'home#about', as: 'about'

  get 'userpass/reset' => 'reset#send', as: 'reset_userpass'

  put 'userpass/reset' => 'reset#send', as: 'user_reset_userpass'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calorie.rb
class Calorie < ApplicationRecord

    validates :name, presence: true
    validates :calorie, numericality: {only_integer: true}
    validates :weight, numericality: {only_integer: true}
    validates :is_active, inclusion: {in: [true, false]}
    validates :yomi, presence: true

    def self.search(search)
      if search
        Calorie.where(['name LIKE ?', "%#{search}%"])
      else
        Calorie.all
      end
    end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :comments,dependent: :destroy
  attachment :image

  with_options presence: true do
    validates :title
    validates :body
    validates :procedure
    validates :material
    validates :image
  end
  validates :calorie, numericality: {only_integer: true}
  validates :is_light, inclusion: {in: [true, false]}
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments,dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  validates :username, presence: true
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人
  
  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

# ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

# フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end

  def already_favorited?(post)
    self.favorites.exists?(post_id: post.id)
  end

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

  def unsubscribe!
    
    ActiveRecord::Base.transaction do
      update!(is_deleted:true)
      comments.each do |comment| 
      comment.destroy! 
      end

      followed.each do |follow| 
        follow.destroy! 
      end

      follower.each do |follow| 
        follow.destroy! 
      end

      favorites.each do |favorite| 
        favorite.destroy! 
      end
        
      posts.each do |post| 
        post.destroy! 
      end

      
    end
    begin
      # 成功時
    rescue => e
      Rails.logger.info "Rendering 500 with Exception: #{e}"
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin_admin!
  def index
    @users = User.page(params[:page]).per(8)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
  @user=User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]="会員ステータスを編集しました。"
      redirect_to admin_users_path
    else
      flash.now[:error]="入力内容に誤りがあります。"
      render:edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:is_deleted)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @all_ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(4).pluck(:post_id))
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @posts = Post.page(params[:page]).per(4)
    if params[:is_light].present?
      @posts = Post.where(is_light: params[:is_light]).page(params[:page]).per(4)
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @user = @post.user
    
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
    redirect_to post_path(@post), notice: "投稿しました"
    else
    render :new
    end
  end
  
  def edit
    @post = Post.find(params[:id])
    if @post.user != current_user
      redirect_to posts_path,alert: '不正なアクセスです'
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
    redirect_to post_path(@post), notice: "更新しました"
    else
    render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :calorie, :body, :image, :material, :procedure, :is_light)
  end

end

app/controllers/reset_controller.rb
class ResetController < ApplicationController

def send

end





end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  
  def follow
    @user = User.find(params[:id])
  end

  def followed
    @user = User.find(params[:id])
  end
  
  def index
    @users = User.page(params[:page]).per(4).where(is_deleted: false)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to users_path, alert: '不正なアクセスです'
    end
  end

  def update
    @user = User.find(params[:id])
    if@user.update(user_params)
    redirect_to user_path(@user)
    else
    render :edit
    end
  end 

  def withdraw
  end
  
  def change
    current_user.unsubscribe!
      sign_out current_user
    redirect_to root_path
    
  end

private 
  def user_params
    params.require(:user).permit(:username,:email,:profile,:profile_image,:is_deleted)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calories_helper.rb
module CaloriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_alert(key)
    case key
    when "alert"
      "warning"
    when "notice"
      "success"
    when "error"
      "danger"
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/reset_helper.rb
module ResetHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
<h2><%= @user.username%>さんの会員情報編集</h2>
  <div class="row mt-5">

    <%=form_for @user, url: admin_user_path, method: :patch do|f| %>
      <table class="table table-borderless">
          <tr class="tr-size">
            <td width="140"><%=f.label :会員ID %></td>
            <td><%= @user.id %></td>
          </tr>
          <tr class="tr-size">
            <td width="140"><%=f.label :ユーザーネーム %></td>
            <td><%= @user.username %></td>
          </tr>
          <tr class="tr-size">
            <td width="140"><%=f.label :メールアドレス %></td>
            <td><%= @user.email %></td>
          </tr>
          <tr class="tr-size">
            <td width="140"><%= f.label :会員ステータス %></td>
            <td><%= f.radio_button :is_deleted, :false %>
                <%=f.label:有効,class: "is_deleted_label" %>
                <%=f.radio_button :is_deleted, :true %>
                <%=f.label:退会済み,class: "is_deleted_label" %>
            </td>
          </tr>
      </table>
      <%= f.submit "変更を保存する",class: "btn btn-primary"%>
    <% end %>

  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row">
  <div class="col-lg-4">   
    <h2 class="mt-5 ml-5 mb-4">会員一覧</h2>
  </div>
        
        <table class="table table-striped table-hover mb-5">
          <tr>
            <th>会員ID</th>
            <th>ユーザー名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
          <% @users.each do|user| %>
          <tr>
            <td>
              <%=user.id%>
            </td>
            <td>
              <%= link_to admin_user_path(user) do %>
                <%=user.username%>
              <% end %>
            </td>
            <td>
              <%=user.email%>
            </td>
            <td>
              <%if user.is_deleted==false%>
              有効
              <%else%>
              退会済み
              <%end%>
            </td>
          </tr>
          <% end %>
        </table>
  </div>  
  <div class="row offset-5">  
  <%= paginate @users %>
</div>

app/views/admin/users/show.html.erb
<div class="container">
<h2><%=@user.username%>さんの会員詳細</h2>
  <div class="row mt-5">
      <table class="table table-borderless">
        <tr class="tr-size">
          <td width="140">会員ID</td> 
          <td><%= @user.id%>
            <% if @user.is_deleted==false %>
              <span class="badge badge-primary">有効会員</span>
            <% else %>
                <span class="badge badge-danger">退会済み</span>
            <% end %>
            </td>
        </tr>
        <tr class="tr-size">
          <td width="140">ユーザー名</td>
          <td><%=@user.username%></td>
        </tr>
        <tr class="tr-size">
          <td width="140">メールアドレス</td>
          <td><%=@user.email%></td>
        </tr>
      </table>
      <%=link_to "編集する",edit_admin_user_path,class: "btn btn-primary mx-3"%>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <h1>編集</h1>
    <%=link_to "Back",user_path(@user)%>
    <div class="row mt-5 offset-1">
      <div class="col-lg-12">
          <% if @user.errors.any? %>
            <%= pluralize(@user.errors.count, "error") %> prohibited this object from being saved: not successfully

            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>          
          <% end %>
  
        <table class="table table-borderless">
          <%= form_for @user do |f|%>
            <tr>
              <td>
                <%=f.label :profile_image %>
                <%= attachment_image_tag @user, :profile_image, :fill, 200,200, format: "jpeg", fallback: 'no-image.png', onClick: "$('.img_field').click()", class: "center-block img-thumbnail img-responsive img_prev pull-left profile-img", fallback: "no_image.jpg", :width => "200", :height => "200" %>
                <%=f.attachment_field :profile_image, class: 'img_field'  %>
              </td>
            </tr>
            <tr class="tr-size">            
              <td><%=f.label :username %></td>
              <td><%=f.text_field :username %></td>
              
            </tr>
            <tr class="tr-size">
              <td width="100"><%=f.label :email %></td>
              <td><%=f.text_field :email %></td>
            </tr>
            <tr class="tr-size">                       
              <td width="100"><%=f.label :profile %></td>
              <td><%=f.text_field :profile,:size=>"30x10" %></td>
            </tr>
            <tr class="tr-size">
              <td><%=f.submit"更新", class: "btn btn-primary" %></td>
              <td><%= link_to "退会する", withdraw_user_path, class: "btn btn-danger mb-5" %></td>
            </tr>      
          <% end %>
        </table>
      </div>


    </div>
</div>

app/views/users/follow.html.erb
<div class="container">
  <div class="row">
    <h2 class="col-lg-4 mb-5">Follows User</h2>   
    <% if @user.following_user.count == 0 %>
      <p>フォローしている人はいません<p>
    <% else %> 
  </div>      
      <% @user.following_user.where.not(id: current_user.id).each do |user| %>
        <table class="table table-hover table-inverse">
          <tr>
            <th>image</th>
            <th>name</th>
          </tr>
          <tr>
            <td class="image"><%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "rounded-circle pull-left profile-img", fallback: "no_image.jpg",size: "60x60"  %></td>
            <td><%=user.username %></td>
            <td>フォロー数:<%=user.follower.count %></td>
            <td>フォロワー数:<%=user.followed.count %></td>
            <td class="show"><%=link_to"マイページへ",user_path(user.id) %></td>
          </tr>
        </table>
      <% end %>
    <% end %>
</div>

app/views/users/followed.html.erb
<div class="container">
  <div class="row">
    <h2 class="col-lg-4 mb-5">Follower User</h2>   
    <% if @user.following_user.count == 0 %>
      <p>フォロワーはいません<p>
    <% else %> 
  </div>      

      <% @user.follower_user.where.not(id: current_user.id).each do |user| %>
        <table class="table table-hover table-inverse">
            <tr>
              <th>image</th>
              <th>name</th>
            </tr>
            <tr>
              <td class="image"><%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "rounded-circle pull-left profile-img", fallback: "no_image.jpg",size: "60x60"  %></td>
              <td class="name"><%=user.username %></td>
              <td>フォロー数:<%=user.follower.count %></td>
              <td>フォロワー数:<%=user.followed.count %></td>
              <td class="show"><%=link_to"マイページへ",user_path(@user.id) %></td>
            </tr>
        </table>
      <% end %>     
    <% end %>

</div>

app/views/users/index.html.erb
<div class="container">
  <h1>chefs</h1>
  
    <div class="ranking">
        <% @users.each do |user| %>
            <%= link_to user_path(user) do %>
          <div class ="rank">
              <%= attachment_image_tag user, :profile_image, size: "200x200", format: 'jpeg', class: "rounded-circle pull-left profile-img", fallback: "no_image.jpg",size: "200x200" %>
            <% end %>        
              <%=link_to user.username, user_path(user) %>         
              <%= user.posts.count %>投稿
              <div>
                フォロー数:<%= user.follower.count %>
              </div>
              <div>
                フォロワー数:<%= user.followed.count %>
              </div>
            <%# ログインしてるuserのid == user.id %>
              <% unless current_user.id == user.id %>
                <%if current_user.following?(user) %>  
                  <%= link_to 'フォロー外す', unfollow_path(user.id), class: "btn btn-primary",method: :POST %>
                <% else %>
                  <%= link_to 'フォローする', follow_path(user.id), class: "btn btn-success", method: :POST %>
                <% end %>
              <% end %>    
            </div> 
        <% end %>     
    </div>   
  
<div class='rank mt-5'>
  <%= paginate @users %>
</div>

app/views/users/show.html.erb
<div class="container">
  <h1>My page</h1>
    <div class="row mt-5" >
      <div class="col-lg-10">
        <%= attachment_image_tag @user, :profile_image, size: "200x200", format: 'jpeg', class: "rounded-circle pull-left profile-img", fallback: "no_image.jpg",size: "200x200" %>

        <% unless @user == current_user %>
            <% if current_user.following?(@user) %>
              <%= link_to 'フォロー外す', unfollow_path(@user.id),class: "btn btn-primary", method: :POST %>
            <% else %>
            <%= link_to 'フォローする', follow_path(@user.id), class: "btn btn-success", method: :POST %>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-8">
      
        <table class="table table-borderless">
          <tr>
            <th>Username</th>
            <td><%= @user.username %></td>
            <td><%= link_to follows_path(@user.id) do %>
                  <%= "フォロー数: #{@user.follower.count}" %>
                <% end %>
                <%= link_to followed_path(@user.id) do%>
                  <%= "フォロワー数: #{@user.followed.count}" %>
                <% end %>
            </td>
          </tr>
          <tr>
            <th>Profile</th>
            <td><%= @user.profile %></td>
          </tr>

          <tr>
          <% if @user.id == current_user.id%>
            <th>e-mail</th>
            <td><%= @user.email %></td>
          </tr>
            <th><%=link_to"編集",edit_user_path(@user), class: "btn btn-success" %></th>
            <%= link_to "退会する", withdraw_user_path, class: "btn btn-danger mb-5" %>
          </tr>          
          <% end %>      
      </table>
      </div>
    </div>
    <h2>投稿一覧</h2>
    <div class="row mt-5">
      <div class="col-lg-10 offset-4">
        <% @user.posts.each do |post|%>
          
          <ul style="list-style: none;">
          <li>
            <%=attachment_image_tag post, :image, size: "300x300" %>
          </li>
          <li>
            <%=post.title%>
            <% if post.is_light==false %>
              （増量レシピ）
            <% else %>
              （減量レシピ）
            <% end %>
          </li>
          <li>
            <%=link_to "詳細", post_path(post) %>

            <% if @user.id == current_user.id %>
            <%=link_to "編集",edit_post_path(post) %>
            
            <%=link_to "削除",post_path(post), method: :delete, data: {confirm: "削除しますか？"} %>

            <% end %>
          </li>
          <li>
            <%=post.updated_at.strftime("%Y-%m-%d %H:%M") %>更新
          </li>
        </ul>
        <% end %>
      </div>
    </div>









</div>

app/views/users/withdraw.html.erb
<div class="container">
  <div class="row">
    <div class="mt-5 mb-5  col-lg-5 offset-sm-2">
      <h2>本当に退会しますか？</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-5 offset-2">  
      <%=link_to"退会しない",user_path(current_user),class:"btn btn-primary"%>
      <%=link_to"退会する",users_change_path(@user),method: :patch, "data-confirm" => "退会します", class:"btn btn-danger"%>
    </div>
  </div>

</div>